server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  type-aliases-package: com.vplus.demo.userservice.model
  mapper-locations: classpath:mapper/*.xml


  spring:
    resources:
      static-locations: classpath:templates/,classpath:static/
    mvc:
      view:
        prefix: /html/
        suffix: .html